[features]
seeds = false
[programs.localnet]
craft_skins = "CTvt7mspUNotZfaWNXCtUN2uCjSqxDCyD1nvpNQqixKX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/drewriester/.config/solana/drew.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
